general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para travar a tela
    before_sleep_cmd = loginctl lock-session    # Trava antes de suspender o sistema
    after_sleep_cmd = hyprctl dispatch dpms on  # Liga a tela ao acordar
}

# Bloqueia a tela após 5 minutos (300s)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Desliga o monitor após 10 minutos (600s)
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
