# --- PLANO DE FUNDO ---
background {
    monitor =
    path = screenshot # Usa um print da tela atual ou coloque o caminho de uma imagem, ex: /path/to/wallpaper.png
    color = rgba(25, 20, 30, 1.0)

    # Efeito de desfoque
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

# --- CAMPO DE SENHA ---
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(180, 190, 254, 1.0)
    inner_color = rgba(30, 30, 46, 0.8)
    font_color = rgb(205, 214, 244)

    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4"><i>...</i></span>
    hide_input = false

    position = 0, -50
    halign = center
    valign = center
}

# --- RELÓGIO (HORA) ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(205, 214, 244, 1.0)
    font_size = 90
    font_family = JetBrains Mono Nerd Font ExtraBold

    position = 0, 150
    halign = center
    valign = center
}

# --- DATA ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(166, 173, 200, 1.0)
    font_size = 20
    font_family = JetBrains Mono Nerd Font

    position = 0, 70
    halign = center
    valign = center
}
